geschwister(udo, heinz)
geschwister(udo, heinz)
kein_kind(ulrich)
kein_kind(udo)
kein_kind(lutz)
kein_kind(hugo)
kein_kind(fred)
kein_kind(heinz)
kein_kind(peter)
kein_kind(bert)
kein_kind(klaus)
kein_kind(helga)
kein_kind(susanne)
kein_kind(elke)
kein_kind(luise)
kein_kind(steffi)
kein_kind(petra)
kein_kind(christa)
kein_kind(isolde)
kein_kind(erika)
kein_kind(lena)
